### Gram-Schmidt process
#### Intrucstions
In this assignment you will write a function to perform the Gram-Schmidt procedure, which takes a list of vectors and forms an orthonormal basis from this set. As a corollary , the procedure allows us to determine the dimension of the space spanned by the basis vectors, which is equal to or less than the space which the vectors sit.

You'll start by completing a function for 4 basis vectors, before generalising to when an arbitrary number of vectors are given.

#### Matrices in Python
Remember the structure for matrices in **numpy** is,

```python
A[0, 0] A[0, 1] A[0, 2] A[0, 3]
A[1, 0] A[1, 1] A[1, 2] A[1, 3]
A[2, 0] A[2, 1] A[2, 2] A[2, 3]
A[3, 0] A[3, 1] A[3, 2] A[3, 3]
```

You can access the value of each element individually using,

```python
A[n, m]
```

You can also access a whole row a time using,

```python
A[n]
```

Building on last assignment, in this exercise you will need to select whole columns at a time. This can be done with,

```python
A[:, m]
```

which will select the m'th column (starting at zero).

In this exercise, you will need to take the dot product between vectors. This can be done using the **@** operator. To dot product vectors u and v, use the code,

```python
u @ v
```

#### Gram-Schmidt process

$$\vec{u_k} = \vec{v_k} - \sum_{j=1}^{k-1} proj_{\vec{u_j}} (\vec{v_k})$$

$$proj_{\vec{u_j}} (\vec{v_k}) = {\vec{u_j} * \vec{v_k} \over (\vec{u_j})^2} * \vec{u_j}$$

$$\vec{e_k} = {\vec{u_k} \over \|\vec{u_k}\|}$$

In [20]:
import numpy as np
import numpy.linalg as la

In [21]:
verySmallNumber = 1e-14

In [22]:
def gsBasis4(A):
    B = np.array(A, dtype=np.float64)

    B[:, 0] = B[:, 0] / la.norm(B[:, 0])
    B[:, 1] = B[:, 1] - B[:, 1] @ B[:, 0] * B[:, 0]

    if la.norm(B[:, 1]) > verySmallNumber:
        B[:, 1] = B[:, 1] / la.norm(B[:, 1])
    else:
        B[:, 1] = np.zeros_like(B[:, 1])
    
    B[:, 2] = (
        B[:, 2] - B[:, 2] @ B[:, 1] * B[:, 1] - 
        B[:, 2] @ B[:, 0] * B[:, 0]
    )

    if la.norm(B[:, 2]) > verySmallNumber :
        B[:, 2] = B[:, 2] / la.norm(B[:, 2])
    else:
        B[:, 2] = np.zeros_like(B[:, 2])

    B[:, 3] = (
        B[:, 3] - B[:, 3] @ B[:, 2] * B[:, 2] - 
        B[:, 3] @ B[:, 1] * B[:, 1] - 
        B[:, 3] @ B[:, 0] * B[:, 0]
    )

    if la.norm(B[:, 3]) > verySmallNumber :
        B[:, 3] = B[:, 3] / la.norm(B[:, 3])
    else:
        B[:, 3] = np.zeros_like(B[:, 3])
    
    return B


In [23]:
def gsBasis(A):
    B = np.array(A, dtype=np.float64)

    for i in range(B.shape[1]):
        for j in range(i):
            B[:, i] = B[:, i] - B[:, i] @ B[:, j] * B[:, j]
        if la.norm(B[:, i]) > verySmallNumber :
            B[:, i] = B[:, i] / la.norm(B[:, i])
        else:
            B[:, i] = np.zeros_like(B[:, i])
    
    return B

In [24]:
def dimensions(A):
    return np.sum(la.norm(gsBasis(A), axis=0))

#### Test your code

In [25]:
V = np.array([
    [1, 0, 2, 6],
    [0, 1, 8, 2],
    [2, 8, 3, 1],
    [1, -6, 2, 3]
], dtype=np.float64)

In [26]:
gsBasis4(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [27]:
U = gsBasis4(V)
gsBasis4(U)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [28]:
gsBasis(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [29]:
A = np.array([
    [3, 2, 3],
    [2, 5, -1],
    [2, 4, 8],
    [12, 2, 1]
], dtype=np.float64)

In [30]:
gsBasis(A)

array([[ 0.23643312,  0.18771349,  0.22132104],
       [ 0.15762208,  0.74769023, -0.64395812],
       [ 0.15762208,  0.57790444,  0.72904263],
       [ 0.94573249, -0.26786082, -0.06951101]])

In [31]:
dimensions(A)

3.0

In [32]:
B = np.array([
    [6, 2, 1, 7, 5],
    [2, 8, 5, -4, 1],
    [1, -6, 3, 2, 8]
], dtype=np.float64)

In [33]:
gsBasis(B)

array([[ 0.93704257, -0.12700832, -0.32530002,  0.        ,  0.        ],
       [ 0.31234752,  0.72140727,  0.61807005,  0.        ,  0.        ],
       [ 0.15617376, -0.6807646 ,  0.71566005,  0.        ,  0.        ]])

In [34]:
dimensions(B)

3.0

In [35]:
C = np.array([
    [1, 0, 2],
    [0, 1, -3],
    [1, 0, 2]
], dtype=np.float64)

In [36]:
gsBasis(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [37]:
dimensions(C)

2.0