### Identifying special matrices
#### Instructions
In this assignment, you shall write a function that will test if a 4x4 matrix is singular, i.e. to determine if an inverse exists, before calculating it.

You shall use the method of converting a matrix to echelon form, and testing if this fails be leaving zeros that can't be removed on the leading diagonal.

#### Matrices in Python
In the **numpy** package in Python, matrices are indexed using zero for the top-most column and left-most row. I.e, the matrix structure looks like this:

```python
A[0, 0] A[0, 1] A[0, 2] A[0, 3]
A[1, 0] A[1, 1] A[1, 2] A[1, 3]
A[2, 0] A[2, 1] A[2, 2] A[2, 3]
A[3, 0] A[3, 1] A[3, 2] A[3, 3]
```

You can access the value of each element individually using,

```python
A[n, m]
```

which will give the n-th and m-th column (starting with zero). You can also access a whole row at a time using,

```python
A[n]
```

Which you will see will be useful when calculating linear combinations of rows.

In [48]:
import numpy as np

In [57]:
class MatrixIsSingular(Exception):
    pass

In [64]:
def fixRowZero(A):
    if A[0, 0] == 0:
        A[0] = A[0] + A[1]
    if A[0, 0] == 0:
        A[0] = A[0] + A[2]
    if A[0, 0] == 0:
        A[0] = A[0] + A[3]
    if A[0, 0] == 0:
        raise MatrixIsSingular
    A[0] = A[0] / A[0, 0]
    return A

In [65]:
def fixRowOne(A):
    A[1] = A[1] - A[1,  0] * A[0]
    if A[1, 1] == 0:
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,  0] * A[0]
    if A[1, 1] == 0:
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,  0] * A[0]
    if A[1, 1] == 0:
        raise MatrixIsSingular
    A[1] = A[1] / A[1, 1]
    return A

In [66]:
def fixRowTwo(A):
    A[2] = A[2] - A[2, 0] * A[0]
    A[2] = A[2] - A[2, 1] * A[1]
    if A[2, 2] == 0:
        A[2] = A[2] + A[3]
        A[2] = A[2] - A[2, 0] * A[0]
        A[2] = A[2] - A[2, 1] * A[1]
    if A[2, 2] == 0:
        raise MatrixIsSingular
    A[2] = A[2] / A[2, 2]
    return A

In [67]:
def fixRowThree(A):
    A[3] = A[3] - A[3, 0] * A[0]
    A[3] = A[3] - A[3, 1] * A[1]
    A[3] = A[3] - A[3, 2] * A[2]
    if A[3, 3] == 0:
        raise MatrixIsSingular
    A[3] = A[3] / A[3, 3]
    return A

In [68]:
def isSingular(A):
    B = np.array(A, dtype=np.float64)
    try:
        fixRowZero(B)
        fixRowOne(A)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

#### Test your code

In [69]:
A = np.array([
    [2, 0, 0, 0],
    [0, 3, 0, 0],
    [0, 0, 4, 4],
    [0, 0, 5, 5]
], dtype=np.float64)
isSingular(A)

True

In [70]:
A = np.array([
    [0, 7, -5, 3],
    [2, 8, 0, 4],
    [3, 12, 0, 5],
    [1, 3, 1, 3]
], dtype=np.float64)

In [71]:
fixRowZero(A)

array([[ 1. ,  7.5, -2.5,  3.5],
       [ 2. ,  8. ,  0. ,  4. ],
       [ 3. , 12. ,  0. ,  5. ],
       [ 1. ,  3. ,  1. ,  3. ]])

In [72]:
fixRowOne(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 3.        , 12.        ,  0.        ,  5.        ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [73]:
fixRowTwo(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [74]:
fixRowThree(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])