### PageRank
#### Introduction
**PageRank** (developed by Larry Page and Sergey Brin) revolutionized web search by generating a ranked list of web pages based on the underlying connectivity of the web. The PageRank algorithm is based on an ideal random web surfer who, when reaching a page, goes to the next page by clicking on a link. The surfer has equal probability of clicking any link on the page and, when reaching a page with no links, has equal probability of moving to any other page by typing in its URL. In addition, the surfer may occasionally choose to type in a random URL instead of following the links on a page. The PageRank is the ranked order of the pages from the most to the least probable page the surfer will be viewing.

In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
np.set_printoptions(suppress=True)

$$ \mathbf{r}^{(i+1)} = L \,\mathbf{r}^{(i)}$$

$$L\mathbf{r} = \mathbf{r}$$

In [3]:
L = np.array([
    [0, 1/2, 1/3, 0, 0, 0],
    [1/3, 0, 0, 0, 1/2, 0],
    [1/3, 1/2, 0, 1, 0, 1/2],
    [1/3, 0, 1/3, 0, 1/2, 1/2],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 1/3, 0, 0, 0]
])

Calculation of eigenvalues and vectors

In [4]:
eVals, eVecs = la.eig(L)
order = np.absolute(eVals).argsort()[::-1]
eVals = eVals[order]
eVecs = eVecs[:,order]

r = eVecs[:, 0]
100 * np.real(r / np.sum(r))

array([16.        ,  5.33333333, 40.        , 25.33333333,  0.        ,
       13.33333333])

Power-Iteration method

In [5]:
r = 100 * np.ones(6) / 6
r

array([16.66666667, 16.66666667, 16.66666667, 16.66666667, 16.66666667,
       16.66666667])

In [6]:
r = L @ r
r

array([13.88888889, 13.88888889, 38.88888889, 27.77777778,  0.        ,
        5.55555556])

In [7]:
r = 100 * np.ones(6) / 6
for _ in np.arange(100):
    r = L @ r
r

array([16.        ,  5.33333333, 40.        , 25.33333333,  0.        ,
       13.33333333])

In [8]:
r = 100 * np.ones(6) / 6
lastR = r
r = L @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = L @ r
    i += 1
print(str(i) + " iterations to convergence.")
r

18 iterations to convergence.


array([16.00149917,  5.33252025, 39.99916911, 25.3324738 ,  0.        ,
       13.33433767])

Power-Iteration with **Damping Parameter**

In [9]:
L2 = np.array([
    [0, 1/2, 1/3, 0, 0, 0, 0],
    [1/3, 0, 0, 0, 1/2, 0, 0],
    [1/3, 1/2, 0, 1, 0, 1/3, 0],
    [1/3, 0, 1/3, 0, 1/2, 1/3, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1/3, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1/3, 1]
])

In [10]:
r = 100 * np.ones(7) / 7
lastR = r
r = L2 @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = L2 @ r
    i += 1
print(str(i) + " iterations to convergence.")
r

131 iterations to convergence.


array([ 0.03046998,  0.01064323,  0.07126612,  0.04423198,  0.        ,
        0.02489342, 99.81849527])

To combat this, we use the following formula

$$ M = d \, L + \frac{1-d}{n} \, J,$$

$$ 0 < d < 1 $$

In [12]:
d = 0.5
M = d * L2 + (1 - d) / 7 * np.ones([7, 7])

In [13]:
r = 100 * np.ones(7) / 7
lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = M @ r
    i += 1
print(str(i) + " iterations to convergence.")
r

8 iterations to convergence.


array([13.68217054, 11.20902965, 22.41964343, 16.7593433 ,  7.14285714,
       10.87976354, 17.90719239])

Function that uses the above code for **arbitrary matrices**

In [14]:
def pageRank(linkMatrix, d):
    n = linkMatrix.shape[0]
    M = d * linkMatrix + (1 - d) / n * np.ones([n, n])
    r = 100 * np.ones(n) / n

    lastR = r
    r = M @ r

    while la.norm(lastR - r) > 0.01:
        lastR = r
        r = M @ r

    return r

#### Test your code

In [15]:
L3 = L2

In [19]:
pageRank(L3, 1)

array([ 0.03046998,  0.01064323,  0.07126612,  0.04423198,  0.        ,
        0.02489342, 99.81849527])

In [20]:
pageRank(L3, 0.5)

array([13.68217054, 11.20902965, 22.41964343, 16.7593433 ,  7.14285714,
       10.87976354, 17.90719239])